drop table IF EXISTS LIKES CASCADE;
drop table IF EXISTS FRIEND CASCADE;
drop table IF EXISTS FILM_GENRE CASCADE;
drop table IF EXISTS FILM CASCADE;
drop table IF EXISTS GENRE CASCADE;
drop table IF EXISTS RATING CASCADE;
drop table IF EXISTS USERS CASCADE;